schema:
  - http://localhost:8080/v1/graphql:
      headers:
          x-hasura-admin-secret: squidsquidsquid
# documents: '**/*.graphql'

plugins:
  - typescript-operations
  - typescript-react-apollo
cacheDir: __generated__
