-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."invoices" add column "recipient_token_amount_raw" text
--  not null;
